#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export WH_SDK=$HOME/Workspace/IA/whsdk
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jhorvat/Library/Android/sdk/platform-tools:$WH_SDK/tools"
export ANDROID_HOME="/Users/jhorvat/Library/Android/sdk"
alias git=hub
